<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class VicidailUser extends Model
{
    use HasApiTokens, HasFactory, Notifiable;
    // Define o nome da tabela
    protected $table = 'vicidial_users';

    // Define a chave primária, se não for 'id'
    protected $primaryKey = 'user_id'; // ou o nome da sua chave primária, se diferente

    // Se a tabela não usa timestamps (created_at e updated_at)
    public $timestamps = false; // Altere para true se sua tabela tiver timestamps

    // Campos que podem ser preenchidos
    protected $fillable = [
        'user',
        'pass',
        'full_name',
        'user_level',
        'user_group',
        'phone_login',
        'phone_pass',
        'delete_users',
        'delete_user_groups',
        'delete_lists',
        'delete_campaigns',
        'delete_ingroups',
        'delete_remote_agents',
        'load_leads',
        'campaign_detail',
        'ast_admin_access',
        'ast_delete_phones',
        'delete_scripts',
        'modify_leads',
        'hotkeys_active',
        'change_agent_campaign',
        'agent_choose_ingroups',
        'closer_campaigns',
        'scheduled_callbacks',
        'agentonly_callbacks',
        'agentcall_manual',
        'vicidial_recording',
        'vicidial_transfers',
        'delete_filters',
        'alter_agent_interface_options',
        'closer_default_blended',
        'delete_call_times',
        'modify_call_times',
        'modify_users',
        'modify_campaigns',
        'modify_lists',
        'modify_scripts',
        'modify_filters',
        'modify_ingroups',
        'modify_usergroups',
        'modify_remoteagents',
        'modify_servers',
        'view_reports',
        'vicidial_recording_override',
        'alter_custdata_override',
        'qc_enabled', 'qc_user_level',
        'qc_pass',
        'qc_finish',
        'qc_commit',
        'add_timeclock_log',
        'modify_timeclock_log',
        'delete_timeclock_log',
        'alter_custphone_override',
        'vdc_agent_api_access',
        'modify_inbound_dids',
        'delete_inbound_dids',
        'active',
        'alert_enabled',
        'download_lists',
        'agent_shift_enforcement_override',
        'manager_shift_enforcement_override',
        'shift_override_flag',
        'export_reports',
        'delete_from_dnc',
        'email',
        'user_code',
        'territory',
        'allow_alerts',
        'agent_choose_territories',
        'custom_one',
        'custom_two',
        'custom_three',
        'custom_four',
        'custom_five',
        'voicemail_id',
        'agent_call_log_view_override',
        'callcard_admin',
        'agent_choose_blended',
        'realtime_block_user_info',
        'custom_fields_modify',
        'force_change_password',
        'agent_lead_search_override',
        'modify_shifts',
        'modify_phones',
        'modify_carriers',
        'modify_labels',
        'modify_statuses',
        'modify_voicemail',
        'modify_audiostore',
        'modify_moh',
        'modify_tts',
        'preset_contact_search',
        'modify_contacts',
        'modify_same_user_level',
        'admin_hide_lead_data',
        'admin_hide_phone_data',
        'agentcall_email',
        'modify_email_accounts',
        'failed_login_count',
        'last_login_date',
        'last_ip',
        'pass_hash',
        'alter_admin_interface_options',
        'max_inbound_calls',
        'modify_custom_dialplans',
        'wrapup_seconds_override',
        'modify_languages',
        'selected_language',
        'user_choose_language',
        'ignore_group_on_search',
        'api_list_restrict',
        'api_allowed_functions',
        'lead_filter_id',
        'admin_cf_show_hidden',
        'agentcall_chat',
        'user_hide_realtime',
        'access_recordings',
        'modify_colors',
        'user_nickname',
        'user_new_lead_limit',
        'api_only_user',
        'modify_auto_reports',
        'modify_ip_lists',
        'ignore_ip_list',
        'ready_max_logout',
        'export_gdpr_leads',
        'pause_code_approval',
        'max_hopper_calls',
        'max_hopper_calls_hour',
        'mute_recordings',
        'hide_call_log_info',
        'next_dial_my_callbacks',
        'user_admin_redirect_url',
        'max_inbound_filter_enabled',
        'max_inbound_filter_statuses',
        'max_inbound_filter_ingroups',
        'max_inbound_filter_min_sec',
        'status_group_id',
        'mobile_number',
        'two_factor_override',
        'manual_dial_filter',
        'user_location',
        'download_invalid_files',
        'user_group_two',
        'failed_login_attempts_today',
        'failed_login_count_today',
        'failed_last_ip_today',
        'failed_last_type_today',
        'modify_dial_prefix',
        'inbound_credits',
        'hci_enabled'
    ];
}